name: Test

on:
  pull_request:
    paths:
      - ".github/workflows/test.yml"
      - "**.py"
  push:
    paths:
      - ".github/workflows/test.yml"
      - "**.py"
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os }} / ${{ matrix.python_version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [Ubuntu, Windows, macOS]
        python_version:
          ["3.7", "3.8", "3.9", "3.10", "3.11-dev", "pypy-3.7", "pypy-3.8", "pypy-3.9"]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        name: Install Python ${{ matrix.python_version }}
        with:
          python-version: ${{ matrix.python_version }}
          cache: "pip"

      - name: Run nox
        run: |
          # Need to fix-up PyPy. This can be removed once https://github.com/actions/setup-python/issues/346 lands.
          INTERPRETER=${{ matrix.python_version }}
          INTERPRETER=${INTERPRETER/-/}  # remove the first '-' in "pypy-X.Y" -> "pypyX.Y" to match executable name
          pipx run nox --error-on-missing-interpreters -s tests-${INTERPRETER}
        shell: bash
